name: iOS IPA Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # اجرا فقط وقتی که تگی با پیشوند v پوش بشه (مثلا v1.0.0)

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS IPA (no signing)
        run: flutter build ipa --release --no-codesign

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            iOS IPA built automatically from commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/ipa/Runner.ipa
          asset_name: MyApp-${{ github.ref_name }}.ipa
          asset_content_type: application/octet-stream
