name: Build Flutter iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS IPA (no signing)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nazmino-IPA
          path: build/ios/archive/*.ipa
